default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: diannekatherine
  password:
  host: postgres

development:
  <<: *default
  database: ghgdata_development

test:
  <<: *default
  database: ghgdata_test

production:
  <<: *default
  database: ghgdata_production
  username: ghgdata
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

