default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: ghgdata_development

test:
  <<: *default
  database: ghgdata_test

production:
  <<: *default
  database: ghgdata_production

